# Generated by Django 3.2.8 on 2021-10-28 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manage', '0003_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='uploadExcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_a', models.IntegerField()),
                ('field_b', models.IntegerField()),
                ('field_c', models.IntegerField()),
                ('field_d', models.IntegerField()),
            ],
        ),
    ]
